### ISSUE TITLE
Importar serie (XML)

### ISSUE THREAD

**Issue by lgarmendiadi20dw** [UnaiCorzo/Proyecto#3]
En el `Modelo.java`, en el método de importar un archivo XML, no deja importar una tabla para serie. Seria interesante añadir esa funcionalidad a las ya existentes.

**Comment by Gorka9898** [comment]
Buena idea, estoy de acuerdo

**Comment by UnaiCorzo** [comment]
Ya se ha añadido para la versión v0.1.0-rc2
